### ISSUE TITLE
Ragchew Practice Set Idea

### ISSUE THREAD

**Issue by jsurls** [zoglmannk/Morse-Code-Ninja#14]
Hi Kurt,

Have you considered a practice set that keeps the top 500 words or sentences, replacing common words with abbreviations? It could be useful for ragchew hearing words or sentences with "and" replaced with "es" and "again" with "agn". I know I can do this on my own with the source, but offer the idea as a "Ragchew" dataset.

Thanks in advance!
73
Joey Surls
KI5DDO

**Comment by zoglmannk** [comment]
Thanks, Joey, for the idea! Perhaps you are looking for something like the "Sentences from the Top 500 Words and Abbreviations"? The text file for it is https://github.com/zoglmannk/Morse-Code-Ninja/blob/main/practice-sets/Sentences%20from%20Top%20500%20Words%20and%20Abbreviations.txt . You can also find it on my Morse Code Ninja practice page — https://morsecode.ninja/practice/index.html . You'll need to scroll down about two-thirds of the way down the list of practice sets.

73 de AD0WE

**Comment by jsurls** [comment]
That's exactly it! Well that was easy 🤣

I'll close the feature request and keep chewing on new ideas. Thanks again!

-Joey

**Comment by zoglmannk** [comment]
You're welcome! I'm always open to new ideas. Many of the ideas for practice sets have come from others with a particular need. :)

73 de AD0WE
