### ISSUE TITLE
Except clause syntax error in text2speech.py

### ISSUE THREAD

**Issue by rafiks** [zoglmannk/Morse-Code-Ninja#31]
I had to comment the except clause print statement because it does not like the syntax.
I have python 3.10 in ubuntu Jammy.
        #print(f"I/O error reading aws.properties: {e.errno}, {e.strerror}")

**Comment by zoglmannk** [comment]
Thanks. I will work on fixing this.

**Comment by zoglmannk** [comment]
Hmm... On Python 3.7.7 this works as expected

I/O error reading aws.properties: 2, No such file or directory

**Comment by zoglmannk** [comment]
I have tested this under Python 3.11.1, and this works as expected. If you can provide more details, I can look into it further.
